<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>contexts</key>
	<dict>
		<key>attribute-entities</key>
		<array>
			<dict>
				<key>include</key>
				<string>entities-common</string>
			</dict>
			<dict>
				<key>include</key>
				<string>entities-meta</string>
			</dict>
		</array>
		<key>entities</key>
		<array>
			<dict>
				<key>include</key>
				<string>entities-common</string>
			</dict>
			<dict>
				<key>match</key>
				<string>&amp;</string>
				<key>scope</key>
				<string>invalid.illegal.bad-ampersand.html</string>
			</dict>
		</array>
		<key>entities-common</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.entity.html</string>
					<key>3</key>
					<string>punctuation.definition.entity.html</string>
				</dict>
				<key>match</key>
				<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
				<key>scope</key>
				<string>constant.character.entity.html</string>
			</dict>
		</array>
		<key>entities-meta</key>
		<array>
			<dict>
				<key>match</key>
				<string>{{</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_content_scope</key>
						<string>source.js.embedded.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>scope:source.js</string>
					</dict>
					<dict>
						<key>match</key>
						<string>}}</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>keyword.other.substitution.end.js</string>
					</dict>
				</array>
				<key>scope</key>
				<string>keyword.other.substitution.begin.js</string>
				<key>with_prototype</key>
				<array>
					<dict>
						<key>match</key>
						<string>//</string>
						<key>scope</key>
						<string>invalid.illegal</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>\[\[</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_content_scope</key>
						<string>source.js.embedded.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>scope:source.js</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\]\]</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>keyword.other.substitution.end.js</string>
					</dict>
				</array>
				<key>scope</key>
				<string>keyword.other.substitution.begin.js</string>
				<key>with_prototype</key>
				<array>
					<dict>
						<key>match</key>
						<string>//</string>
						<key>scope</key>
						<string>invalid.illegal</string>
					</dict>
				</array>
			</dict>
		</array>
		<key>main</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.xml.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;\?)(xml)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.preprocessor.xml.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\?&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-generic-attribute</string>
					</dict>
					<dict>
						<key>include</key>
						<string>string-double-quoted</string>
					</dict>
					<dict>
						<key>include</key>
						<string>string-single-quoted</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>&lt;!--</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>comment.block.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>--\s*&gt;</string>
						<key>pop</key>
						<true/>
					</dict>
					<dict>
						<key>match</key>
						<string>--</string>
						<key>scope</key>
						<string>invalid.illegal.bad-comments-or-CDATA.html</string>
					</dict>
				</array>
				<key>scope</key>
				<string>punctuation.definition.comment.html</string>
			</dict>
			<dict>
				<key>match</key>
				<string>&lt;!</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.sgml.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?i:DOCTYPE)</string>
						<key>push</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.tag.sgml.doctype.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?=&gt;)</string>
								<key>pop</key>
								<true/>
							</dict>
							<dict>
								<key>match</key>
								<string>"[^"&gt;]*"</string>
								<key>scope</key>
								<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
							</dict>
						</array>
						<key>scope</key>
						<string>entity.name.tag.doctype.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\[CDATA\[</string>
						<key>push</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>constant.other.inline-data.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>]](?=&gt;)</string>
								<key>pop</key>
								<true/>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>(\s*)(?!--|&gt;)\S(\s*)</string>
						<key>scope</key>
						<string>invalid.illegal.bad-comments-or-CDATA.html</string>
					</dict>
				</array>
				<key>scope</key>
				<string>punctuation.definition.tag.html</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.custom.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)([a-z_][a-z0-9:_]*-[a-z0-9:_-]+)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.custom.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?: ?/)?&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>0</key>
					<string>meta.tag.style.begin.html</string>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.style.html</string>
				</dict>
				<key>match</key>
				<string>(?:^\s+)?(&lt;)((?i:style))\b(?![^&gt;]*/&gt;)</string>
				<key>push</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>0</key>
							<string>meta.tag.style.end.html</string>
							<key>1</key>
							<string>punctuation.definition.tag.begin.html</string>
							<key>2</key>
							<string>entity.name.tag.style.html</string>
							<key>3</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
						<key>match</key>
						<string>(?i)(&lt;/)(style)(&gt;)</string>
						<key>pop</key>
						<true/>
					</dict>
					<dict>
						<key>match</key>
						<string>&gt;</string>
						<key>push</key>
						<array>
							<dict>
								<key>meta_content_scope</key>
								<string>source.css.embedded.html</string>
							</dict>
							<dict>
								<key>include</key>
								<string>scope:source.css</string>
							</dict>
						</array>
						<key>scope</key>
						<string>meta.tag.style.begin.html punctuation.definition.tag.end.html</string>
						<key>with_prototype</key>
						<array>
							<dict>
								<key>match</key>
								<string>(?i)(?=&lt;/style)</string>
								<key>pop</key>
								<true/>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string></string>
						<key>push</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.tag.style.begin.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?=&gt;)</string>
								<key>pop</key>
								<true/>
							</dict>
							<dict>
								<key>include</key>
								<string>tag-stuff</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>0</key>
					<string>meta.tag.script.begin.html</string>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.script.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)(?![^&gt;]*(?i:type.?=.?text/((?!javascript).*)))</string>
				<key>push</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>0</key>
							<string>meta.tag.script.end.html</string>
							<key>1</key>
							<string>comment.block.html punctuation.definition.comment.html</string>
							<key>2</key>
							<string>punctuation.definition.tag.begin.html</string>
							<key>3</key>
							<string>entity.name.tag.script.html</string>
							<key>4</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
						<key>match</key>
						<string>(?i)(--&gt;)?\s*(&lt;/)(script)(&gt;)</string>
						<key>pop</key>
						<true/>
					</dict>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<string>meta.tag.script.begin.html punctuation.definition.tag.end.html</string>
							<key>2</key>
							<string>comment.block.html punctuation.definition.comment.html</string>
						</dict>
						<key>match</key>
						<string>(&gt;)\s*(&lt;!--)?</string>
						<key>push</key>
						<array>
							<dict>
								<key>meta_content_scope</key>
								<string>source.js.embedded.html</string>
							</dict>
							<dict>
								<key>include</key>
								<string>scope:source.js</string>
							</dict>
						</array>
						<key>with_prototype</key>
						<array>
							<dict>
								<key>match</key>
								<string>(?i)(?=(--&gt;)?\s*&lt;/script)</string>
								<key>pop</key>
								<true/>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string></string>
						<key>push</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.tag.script.begin.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?=&gt;)</string>
								<key>pop</key>
								<true/>
							</dict>
							<dict>
								<key>include</key>
								<string>tag-stuff</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.structure.any.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)((?i:body|head|html)\b)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.structure.any.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.block.any.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)((?i:address|blockquote|dd|div|section|article|aside|header|footer|nav|menu|dl|dt|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|pre)\b)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.block.any.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.block.any.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)((?i:hr)\b)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.block.any.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?: ?/)?&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.block.form.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)((?i:form|fieldset)\b)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.block.form.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.inline.any.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)((?i:abbr|acronym|area|b|base|basefont|bdo|big|br|caption|cite|code|del|dfn|em|font|head|html|i|img|ins|isindex|kbd|li|link|map|meta|noscript|param|q|s|samp|script|small|span|strike|strong|style|sub|sup|title|tt|u|var)\b)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.inline.any.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?: ?/)?&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.inline.form.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)((?i:button|input|label|legend|optgroup|option|select|textarea)\b)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.inline.form.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?: ?/)?&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.inline.a.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)((?i:a)\b)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.inline.a.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?: ?/)?&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.inline.table.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)((?i:col|colgroup|table|tbody|td|tfoot|th|thead|tr)\b)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.inline.table.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?: ?/)?&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>invalid.illegal.uppercase-custom-tag-name.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)([A-Za-z0-9:_]+-[A-Za-z0-9:_-]+)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.custom.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?: ?/)?&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>punctuation.definition.tag.begin.html</string>
					<key>2</key>
					<string>entity.name.tag.other.html</string>
				</dict>
				<key>match</key>
				<string>(&lt;/?)([a-zA-Z0-9:]+)</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>meta.tag.other.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>(?: ?/)?&gt;</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.tag.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>tag-stuff</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>include</key>
				<string>entities</string>
			</dict>
			<dict>
				<key>include</key>
				<string>entities-meta</string>
			</dict>
			<dict>
				<key>match</key>
				<string>&lt;&gt;</string>
				<key>scope</key>
				<string>invalid.illegal.incomplete.html</string>
			</dict>
		</array>
		<key>string-double-quoted</key>
		<array>
			<dict>
				<key>match</key>
				<string>"</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>string.quoted.double.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>"</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.string.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>entities</string>
					</dict>
				</array>
				<key>scope</key>
				<string>punctuation.definition.string.begin.html</string>
			</dict>
		</array>
		<key>string-single-quoted</key>
		<array>
			<dict>
				<key>match</key>
				<string>'</string>
				<key>push</key>
				<array>
					<dict>
						<key>meta_scope</key>
						<string>string.quoted.single.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string>'</string>
						<key>pop</key>
						<true/>
						<key>scope</key>
						<string>punctuation.definition.string.end.html</string>
					</dict>
					<dict>
						<key>include</key>
						<string>entities</string>
					</dict>
				</array>
				<key>scope</key>
				<string>punctuation.definition.string.begin.html</string>
			</dict>
		</array>
		<key>tag-class-attribute</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>meta.attribute-with-value.class.html</string>
					<key>2</key>
					<string>entity.other.attribute-name.class.html</string>
					<key>3</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<key>match</key>
				<string>(?:^|\s+)\b((class)\b\s*(\$?=)\s*)</string>
				<key>push</key>
				<array>
					<dict>
						<key>match</key>
						<string>"</string>
						<key>scope</key>
						<string>punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.class.html string.quoted.double.html</string>
							</dict>
							<dict>
								<key>meta_content_scope</key>
								<string>meta.class-name.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>"</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>include</key>
								<string>attribute-entities</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>'</string>
						<key>scope</key>
						<string>punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.class.html string.quoted.single.html</string>
							</dict>
							<dict>
								<key>meta_content_scope</key>
								<string>meta.class-name.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>'</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>include</key>
								<string>attribute-entities</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>(?:[^\s&lt;&gt;/'"]|/(?!&gt;))+</string>
						<key>scope</key>
						<string>meta.attribute-with-value.class.html string.unquoted.html meta.class-name.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string></string>
						<key>pop</key>
						<true/>
					</dict>
				</array>
			</dict>
		</array>
		<key>tag-event-attribute</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>meta.attribute-with-value.event.html</string>
					<key>2</key>
					<string>entity.other.attribute-name.event.html</string>
					<key>3</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<key>match</key>
				<string>(?x)\s*\b((
onabort|onautocomplete|onautocompleteerror|onblur|oncancel|oncanplay|
oncanplaythrough|onchange|onclick|onclose|oncontextmenu|oncuechange|
ondblclick|ondrag|ondragend|ondragenter|ondragexit|ondragleave|ondragover|
ondragstart|ondrop|ondurationchange|onemptied|onended|onerror|onfocus|
oninput|oninvalid|onkeydown|onkeypress|onkeyup|onload|onloadeddata|
onloadedmetadata|onloadstart|onmousedown|onmouseenter|onmouseleave|
onmousemove|onmouseout|onmouseover|onmouseup|onmousewheel|onpause|onplay|
onplaying|onprogress|onratechange|onreset|onresize|onscroll|onseeked|
onseeking|onselect|onshow|onsort|onstalled|onsubmit|onsuspend|
ontimeupdate|ontoggle|onvolumechange|onwaiting)\b\s*(\$?=)\s*)</string>
				<key>push</key>
				<array>
					<dict>
						<key>match</key>
						<string>"</string>
						<key>scope</key>
						<string>string.quoted.double punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.event.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>"</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>string.quoted.double punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string></string>
								<key>push</key>
								<string>scope:source.js</string>
								<key>with_prototype</key>
								<array>
									<dict>
										<key>match</key>
										<string>(?=")</string>
										<key>pop</key>
										<true/>
									</dict>
									<dict>
										<key>include</key>
										<string>attribute-entities</string>
									</dict>
								</array>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>'</string>
						<key>scope</key>
						<string>string.quoted.single punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.event.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>'</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>string.quoted.single punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string></string>
								<key>push</key>
								<string>scope:source.js</string>
								<key>with_prototype</key>
								<array>
									<dict>
										<key>match</key>
										<string>(?=')</string>
										<key>pop</key>
										<true/>
									</dict>
									<dict>
										<key>include</key>
										<string>attribute-entities</string>
									</dict>
								</array>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string></string>
						<key>pop</key>
						<true/>
					</dict>
				</array>
			</dict>
		</array>
		<key>tag-generic-attribute</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>meta.attribute-with-value.html</string>
					<key>2</key>
					<string>entity.other.attribute-name.html</string>
					<key>3</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<key>match</key>
				<string>(?:^|\s+)(([a-zA-Z0-9:\-_.]+)\s*(\$?=)\s*)</string>
				<key>push</key>
				<array>
					<dict>
						<key>include</key>
						<string>entities-meta</string>
					</dict>
					<dict>
						<key>match</key>
						<string>"</string>
						<key>scope</key>
						<string>punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.html string.quoted.double.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>"</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>include</key>
								<string>attribute-entities</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>'</string>
						<key>scope</key>
						<string>punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.html string.quoted.single.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>'</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>include</key>
								<string>attribute-entities</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>(?:[^\s&lt;&gt;/'"]|/(?!&gt;))+</string>
						<key>scope</key>
						<string>meta.attribute-with-value.html string.unquoted.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string></string>
						<key>pop</key>
						<true/>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>entity.other.attribute-name.html</string>
				</dict>
				<key>match</key>
				<string>\s+([a-zA-Z0-9:\-_.]+)</string>
			</dict>
		</array>
		<key>tag-id-attribute</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>meta.attribute-with-value.id.html</string>
					<key>2</key>
					<string>entity.other.attribute-name.id.html</string>
					<key>3</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<key>match</key>
				<string>(?:^|\s+)\b((id)\b\s*(\$?=)\s*)</string>
				<key>push</key>
				<array>
					<dict>
						<key>match</key>
						<string>"</string>
						<key>scope</key>
						<string>punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.id.html string.quoted.double.html</string>
							</dict>
							<dict>
								<key>meta_content_scope</key>
								<string>meta.toc-list.id.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>"</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>include</key>
								<string>attribute-entities</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>'</string>
						<key>scope</key>
						<string>punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.id.html string.quoted.single.html</string>
							</dict>
							<dict>
								<key>meta_content_scope</key>
								<string>meta.toc-list.id.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string>'</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>include</key>
								<string>attribute-entities</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>(?:[^\s&lt;&gt;/'"]|/(?!&gt;))+</string>
						<key>scope</key>
						<string>meta.attribute-with-value.id.html string.unquoted.html meta.toc-list.id.html</string>
					</dict>
					<dict>
						<key>match</key>
						<string></string>
						<key>pop</key>
						<true/>
					</dict>
				</array>
			</dict>
		</array>
		<key>tag-stuff</key>
		<array>
			<dict>
				<key>include</key>
				<string>tag-id-attribute</string>
			</dict>
			<dict>
				<key>include</key>
				<string>tag-class-attribute</string>
			</dict>
			<dict>
				<key>include</key>
				<string>tag-style-attribute</string>
			</dict>
			<dict>
				<key>include</key>
				<string>tag-event-attribute</string>
			</dict>
			<dict>
				<key>include</key>
				<string>tag-generic-attribute</string>
			</dict>
		</array>
		<key>tag-style-attribute</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>meta.attribute-with-value.style.html</string>
					<key>2</key>
					<string>entity.other.attribute-name.style.html</string>
					<key>3</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<key>match</key>
				<string>(?:^|\s+)\b((style)\b\s*(\$?=)\s*)</string>
				<key>push</key>
				<array>
					<dict>
						<key>match</key>
						<string>"</string>
						<key>scope</key>
						<string>string.quoted.double punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.style.html</string>
							</dict>
							<dict>
								<key>meta_content_scope</key>
								<string>source.css</string>
							</dict>
							<dict>
								<key>match</key>
								<string>"</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>string.quoted.double punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string></string>
								<key>push</key>
								<array>
									<dict>
										<key>include</key>
										<string>CSS.sublime-syntax#rule-list-body</string>
									</dict>
								</array>
								<key>with_prototype</key>
								<array>
									<dict>
										<key>match</key>
										<string>(?=")</string>
										<key>pop</key>
										<true/>
									</dict>
									<dict>
										<key>include</key>
										<string>attribute-entities</string>
									</dict>
								</array>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string>'</string>
						<key>scope</key>
						<string>string.quoted.single punctuation.definition.string.begin.html</string>
						<key>set</key>
						<array>
							<dict>
								<key>meta_scope</key>
								<string>meta.attribute-with-value.style.html</string>
							</dict>
							<dict>
								<key>meta_content_scope</key>
								<string>source.css</string>
							</dict>
							<dict>
								<key>match</key>
								<string>'</string>
								<key>pop</key>
								<true/>
								<key>scope</key>
								<string>string.quoted.single punctuation.definition.string.end.html</string>
							</dict>
							<dict>
								<key>match</key>
								<string></string>
								<key>push</key>
								<array>
									<dict>
										<key>include</key>
										<string>CSS.sublime-syntax#rule-list-body</string>
									</dict>
								</array>
								<key>with_prototype</key>
								<array>
									<dict>
										<key>match</key>
										<string>(?=')</string>
										<key>pop</key>
										<true/>
									</dict>
									<dict>
										<key>include</key>
										<string>attribute-entities</string>
									</dict>
								</array>
							</dict>
						</array>
					</dict>
					<dict>
						<key>match</key>
						<string></string>
						<key>pop</key>
						<true/>
					</dict>
				</array>
			</dict>
		</array>
	</dict>
	<key>file_extensions</key>
	<array>
		<string>html</string>
		<string>htm</string>
	</array>
	<key>name</key>
	<string>Web Component</string>
	<key>scope</key>
	<string>text.html.basic</string>
</dict>
</plist>
